### ISSUE TITLE
3D Secure not working

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/braintree-plugin-for-nopcommerce#12]
> Nopcommerce Version 4.4
> 
> Once enabled with Braintree payment providing all fields which works fine without 3D Secure.
> When 3D Secure is enabled, at the payment process it throws an error saying "The given key 'CardNonce' was not present in the dictionary."
> 
> With 3DS it only asks for Card Number, Expiration Date and CVV but on providing those, the error it give is as above and stop there whereas without 3DS, it asks for Name too and works fine completing the payment.

Source: https://www.nopcommerce.com/boards/topic/91531/braintree-payment-3d-secure-not-working

**Comment by skoshelev** [comment]
This error occurs if the user failed to pass the 3D Secure verification. For 4.50, we added handling of this situation and now display a user-friendly error.

Closed #12
