### ISSUE TITLE
Bug: View Configure.cshtml was not found

### ISSUE THREAD

**Issue by Asrothear** [nopSolutions/braintree-plugin-for-nopcommerce#14]
After freshly installing Braintree i tried to open the configuration Panel, i got greeted with the message
```
We're sorry, an internal error occurred.
Our supporting staff has been notified of this error and will address the issue shortly.
We apologize for the inconvenience.
Please try clicking your browsers 'back' button or try reloading the home page.
If you continue to receive this message, please try again in a little while.
Thank you for your patience.
```
So after looking into the logs i got the following message;
`The view '~/Plugins/Payments.Braintree/Views/Configure.cshtml' was not found. The following locations were searched:
~/Plugins/Payments.Braintree/Views/Configure.cshtml`

the file is in fact existing in the directory:
`/var/www/nopCommerce/Plugins/Payments.BrainTree/Views/Configure.cshtml`

![image](https://github.com/nopSolutions/braintree-plugin-for-nopcommerce/assets/38018660/34d3139e-b567-4cf2-9ca1-e261db52465a)

```
nopCommerce Version: 4.60.6
OS: Unix 5.15.0.101
ASP.NET Info: .NET 7.0.3
Full trust level: Yes
````

```
[Unit]
Description=nopCommerce app running on ubuntu

[Service]
WorkingDirectory=/var/www/nopCommerce
ExecStart=/usr/bin/dotnet /var/www/nopCommerce/Nop.Web.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=nopCommerce
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

[Install]
WantedBy=multi-user.target
```

**Comment by skoshelev** [comment]
Hi, @Asrothear. Thank you for reporting the problem, we analyzed the situation and found a problem in the configuration of the installation package. The new corrected package has already been uploaded to the marketplace.

Closed #14
