### ISSUE TITLE
Customer Vault

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/braintree-plugin-for-nopcommerce#4]
I am having an issue with your Braintree plugin. We have a client site we are using this plugin on. We have configured the plugin with live production keys, and did a live production test, but the Customer Name does not seem to be getting pulled through to the Braintree reports. The specific reports within Braintree where we see this occurring is under "Disbursement Summary". It does not show on the summary screen, and if you expand the specific order, the entire customer information portion is blank. Based on the documentation for the plugin, it seems like this information should be brought over. Do you have any suggestions of things I could try?

**Comment by njakes** [comment]
I am also having an issue with this.  Have you found a fix for this @cklenk? I know that Braintree offers the ability to modify the Transaction Sales Call but I have yet to find a way to do that with nopCommerce.

**Comment by cklenk** [comment]
@njakes Yes I was able to modify the source code of the plugin. I added extra data to the requests to the customer, address and transaction options. That was all under the ProcessPayment method. I also passed in store in vault in the transaction options request. I hope that helps you out.

**Comment by njakes** [comment]
Did you use any of the coding found here: https://developers.braintreepayments.com/reference/request/transaction/sale/dotnet

If not would you be willing to share some of the changes that you have made?

**Comment by cklenk** [comment]
@njakes Yes I did follow most of that. Here is a copy of what I did for you if you want to review.

[BrainTreeCode](https://gist.github.com/cklenk/8b110bcb49b666b6c19221b37d75fd12)

**Comment by skoshelev** [comment]
Closed #4
