### ISSUE TITLE
Support PSD2

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/braintree-plugin-for-nopcommerce#5]
I have been monitoring the new regulations in EU regarding 3DS secure and want to provide you with the impact to your business.

As a technology partner offering PayPal Pro and or Braintree to your customers, your online checkout product will need to comply with a new European Union directive requiring Strong Customer Authentication (SCA). The directive applies from 14 September 2019, but card issuers are working towards SCA by April 2019 so that their systems are fully operational by the deadline. Because you’re offering a PayPal Pro solution to your customers to accept card payments on their website, you’ll need to update your checkout product to meet card issuers’ SCA obligations.  Below are a couple links to familiarize your team with the new requirements. Robert is also here to help. Once you are compliant Robert will need to collect your merchant enablement link. Please feel free to reach out with any questions

More info https://www.braintreepayments.com/blog/understanding-and-preparing-for-psd2-strong-customer-authentication/

**Comment by jamster1981** [comment]
Hi. We use this plugin on our website but I see there has been no updates or reference to the new PSD2 compliance. Any suggestions?

**Comment by jigarsangoi** [comment]
Any update on this ? @AndreiMaz

**Comment by skoshelev** [comment]
Closed #5
