### ISSUE TITLE
Error Incorrect Content-Type:

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/braintree-plugin-for-nopcommerce#6]
nopCommer version: 4.0 & 4.10

Getting this exception "Incorrect Content-Type:" when user try to do payment. please follow this link as they described issue. please solve this issue as soon as possible @AndreiMaz 

[https://www.nopcommerce.com/boards/t/50722/braintree-plug-in-error.aspx](https://www.nopcommerce.com/boards/t/50722/braintree-plug-in-error.aspx)

**Comment by skoshelev** [comment]
Already fixed by [this commit](https://github.com/nopSolutions/braintree-plugin-for-nopcommerce/commit/76640241f522c0ce885699b96bb50130743d7d6e)

**Comment by jigarsangoi** [comment]
There is still error in multi step checkout process @skoshelev . Kindly check in multi step checkout process

**Comment by skoshelev** [comment]
Hi @jigarsangoi. What version of nopCommerce do you use?

**Comment by jigarsangoi** [comment]
nopCommerce version : 4.10
Braintree plugin version : 1.41

**Comment by skoshelev** [comment]
This is very strange, I see the necessary changes in the code, but they do not seem to be in the plugin in the store.
You can update the plugin yourself. To do this, add the following code:

```
//set postback values (we cannot access "Form" with "GET" requests)
if (Request.Method != WebRequestMethods.Http.Get)
	return View("~/Plugins/Payments.BrainTree/Views/PaymentInfo.cshtml", model);
```
to the PaymentBrainTreeViewComponent.Invoke method instead of the line with comment `// set postback values`

Or you can wait until we update the plugin for nopCommerce 4.20. The modified version for 4.10 will also be included there.

**Comment by jigarsangoi** [comment]
I have same lines of code in PaymentBrainTreeViewComponent.Invoke method
I downloaded code yesterday because I have to integrate 3DS but seems this things is still an issue.

Also can you help me How can we integrate 3DS with this payment plugin. Once ready I can collaborate my code here

**Comment by skoshelev** [comment]
Hi @jigarsango. I found a code problem see the correct one version:

```
//set postback values (we cannot access "Form" with "GET" requests)
if (Request.Method == WebRequestMethods.Http.Get)
	return View("~/Plugins/Payments.BrainTree/Views/PaymentInfo.cshtml", model);
```

As for 3DS, we are also considering a variant of its implementation, but we do not have specific recommendations and advice.

**Comment by jigarsangoi** [comment]
Ok thanks for solving that error @skoshelev 
Another thing is, I implement 3DS2 with braintree for my client in same way you implemented Square & Worldpay payment plugin.

I tested sandbox environment seems all working but still live testing is pending.
If you want after live testing I can raise pull request so you can check my code and do correction if needed & release new plugin version with 3DS2

Please let me know

**Comment by skoshelev** [comment]
Hi @jigarsangoi If you can share your decision, we will be happy to analyze and implement it.
